doc.type.html
html. lang.en
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’welcome to covid strings1’
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go 
heading1=keywords
heading2=online references
heading3=script templates
filename=covid strings key word 1.js
let original string=”
let word to add-
let updated string {original string} {word to add}
console log updated string
<header.html>
keywords
key search words for covid strings1
covid strings1 key word list=[bleach,rona,95,flu,tracker,875*.89,vaccinated,1918,100,000,negative]
string manager non-concatenated
insert string(entity,string)
entity.element.text=string
string manager insert string
string=””
string manger concatenated
insert string(entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings key word list
select characters
edit diffuse property
desired color=green
<header.html>
online references 
links to articles that correspond to phrases in covid strings1
covid strings1 reference pairing list=[a:https://www.politico.com/news/2021/04/23/Trump-bleach-one-year-484399, B: https://www.newsweek.com/timothee-chalamet-plays-coronavirus-snl-hosting-debut-1554385,c:https://www.factcheck.org/2022/05/scicheck-pfizer-documents-show-vaccine-is-highly-effective,d:https://www.npr.org/sections/health-shots/2021/09/07/1033756464/flu-shot-covid-booster,e:covid tracker-bing images
f:cdc:some people did take bleach to protect from coronavirus(usnews.com) g:trumps disinfectant injection claim has actually caused people to poison themselves(thenewcivilrightsmovement.com),h: Leader behind bleach miracle cure claims trump consumed his product|donald trump |the guardian,i:how soon will you start building immunity after getting the covid-19 vaccine? -goodrx, 
j:https://www.cnn.com/2020/04/16/health/spanish-flu-coronavirus-lessons-learned/index.k:html,100,000 more covid deaths seen unless us changes its ways |ap news,l:the coronavirus (covid19) pandemics impact on mental health-pmc (nih.gov)]
<header.html>
script templates
code for accessing the references
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
a =pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet(this.entity)
d=pc.createscript(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet(this.entity)
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
f=pc.createscript(f);
f.attributes.add(foobar,{type:entity});
f.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
h=pc.create script(h);
h.attributes.add(foobar, {type: entity});
h.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
i=pc.create script(i);
i.attributes.add(foobar,{type:entity});
i.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
j=pc.create script(j);
j.attributes.add(foobar,{type:entity});
j.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
k=pc.create script(k);
k.attributes.add(foobar, {type:entity});
k.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
l=pc.create script(l);
l.attributes.add(foobar,{type:entity});
l.prototype.initialize=function() 
console.log(this.foobar.name);
return filename
