<doc.type.HTML>
<script>
FileName=Covid Strings1 .JS
Console.Log(Covid Strings1 )
Java.Awt Graphics
Var Audio = New Audio
Audio.Play();
JButton Random Button
New JButton (Set Random Color)
Private Final J Button Option Button=
New J Button (Change Color)
Public Fun With Graphics(){
JPanel Color Panel=New J Panel();
 Add (Panel,Center )
Add(Button);
Button Add ActionListener(New Action Listener)
Override 
SetBackground(New Color)
Panel.Add(OptionButton);
Add ActionListener(New Action Listener(){
Override 
Public Void ActionPerformed(ActionEvent E){
ShowDialog(This)
If(Background!=Null)
Set.Background
Add(South)
JFrame
Set Title(1)
Set( Exit_On_Close);
SetSize
Set 
<Label Id=LblScore>Zero</Label>
(IMG) 
Src =Www.Google.Com/Intl/En_com/Images/Logo_plain.Png;
GetElementById
AppendChild
GetElementbyId
Score.InnerHTML
PhraseList=[non -concatenated hello covid world,dont eat bleach,could you please get vaccinated,Good bye covid world,dont overcrowd hospital capacity,are we going back To 1918,there have been 100,000 reported deaths so far,the covid tracker shows] 
Concatenated [you+should+get+tested,pfizer+is+95%+effective,you+should+not+forget+your+flu+shot,+snl+nailed+a+rona+christmas+There+have+been+some+negative+effects,+some+of+these+include+suicide,the+best+thing+to+do+is+practice+continuity+safely,+in+short+you+should+not+change+your+behavoir+much] 
Math Problems List=[if a covid value c equals 3 is added to the double of the value its equal to what do you get?, a covid value represented by a variable c is quadrupled and then added by f what is the resulting Product?, If the CDCs covid tracker has 50,000 cases 35,000 cases were reported last week how many cases happened? The Cov19 emergency alert system was installed On March 12 2020 after 2 weeks there were 1975 calls if the rate of calls was 5 per hour how many calls happened after the 1st week?, Town A1s Annual Thanksgiving Parade Happens On November 19 A1s public health guidelines require that events of more than 20,000 people be held only if the positivity rate is <=5%  the current positivity rate is 6 1/3% and the parade is next week could it be held? if a decision could be made no later than the 16th and the amount of precautions taken include 10 cartons of 100 masks and 6ft of distancing can the parade still happen?]
[a+knock+off+vaccine+company+promises+to+deliver+a+vaccine+within+2+weeks+if+the+standard+timeline+is+4+weeks+how+much+damage+can+happen?
if+a+poll+on+this+question+showed+that+92 percent+of+republicans+thought+that+he+was+joking+when+it+came+to+bleach+how+many+cf+those+people+risked+illness?,if+875+people+were+reported+to+a+covid+hotline+because+they+thought+injecting+bleach+cured+covid+and+89%+of+them+said+they+believed+trump+how+many+people +out+of+the+total+believed+trump?
If+the+margin+of+error+is+Fifty And  Five Hundreths+Percent+what+is+the+range?,a+news+report+suggested+that+the+level2+emergency+will+continue+for+another+week+if+the+rate+is+>3% if+it+is+currently+2.25%+would+it+continue? ,if + 4 people+ took+an+unknown+number+of+shots+from+pfizers+vaccine+at+3:45pm +on+october 7th when+would+it+expire?]
Sentence List=[Pfizer has a 95% effective vaccine,the+most+obvious+similarity+between+covid+and+the+spanish+flu+is+that+they+were+global+pandemics,any+covid+tracker+is+a+representation+of+data+at+a+specific+place+and+time]
 Multiple Choice List=[1: a Hydrogen Peroxide,  b, ammonium nitrate, c bleach , d Green Eggs And Ham 2: a rona, b green, c krona, d white 3: a tested, b a piercing, c a TI-82 graphing Calculator, d a mcdonalds happy meal 4 : a bienvenu, b hello, c nihau, d hola 
5: a 55, b 95, C 88, D 66, 6 : a oversaturate, b overcrowd, c synthesize, d crowd-surf 7 : a flu, b meningits, c dogs rabies, d archery 8 : a tracker, b map, c graph positiioning system, d lockdown 
9: a effects, b things, c results, d impacts 10: a snow throwing, b vaccinated, c off qanon, d snowballing 11: a 1918, b 1919, c -2045, d -1985 12: a 100,000 B A google, c a bevy, d a number with zero sig figs 
13: a negative b netural c firework-like d Wanting 14: a changes, b continuity, c sameness, d parity,  
15 :a behavoir, b Outlook, c stress-level, d mindset, 16: a serum b vaccine c version of mountain dew d Gatorade knockoff,
 17: a major b only c most obvious d glaring, 18: a hey-ey-ey goodybe, b sayornara, c good night, d goodbye, 19: a poll b prediction c doom scroll d tracker]
Select 
Import Meta.
Select 
(Non-Concatenated)
If Question==Math Problem:
Prompt
Log 
Else:
Select From Multiple Choice
If Question==Multiple Choice:
Select Answer
Else:
Prompt
Log
Const Myclass=NewMyClass( Concatenated) 
Return Category
If Question==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
Import Syntax 
Substring(Start,End)
Userin.Multiple Choice
If User Answer==Correct:
Log True
If User Answer==
Log False
Check Winner :
Log( The Winner is)
else:
Log(No Winner Yet) 
return FileName
