<DocTYPE.HTML>
<script>
    <Html>
<Head>
    <Meta Charset=UTF-Eight
        <Meta Name= Viewport Content=Width=Device-Width,Inital Scale One
    <TITLE> COVID Strings1 Championship >
    </Head>
<Body>
<Link Rel=Stylesheet Href=Styles.CSS
 Brakcet Container{}
            Display: Grid;
            Gap : Tenpx:
            .Matchup{}
            Border : Onepx Solid Zero;
            Padding: Tenpx;
            Text-Align: Center;
FileName=Covid Strings1 Championship Game.JS
Championship Game=(High And Lowest Remaining Seeds) 
Team High Seed= Highest Remaining Seed
Team Low Seed = Lowest Remaining Seed
Console.Log(Covid Strings1 Championship Game)
Create Matchup (Team Low Seed Versus Team High Seed )
Const Matchup Div=matchup
Document.CreateElement 
MatchupDiv.ClassName=(Matchup)
MatchupDiv.InnerHTML =[Matchup]
RoundDiv.AppendChild(Matchup)
Bracket.AppendChild(Round Div)
For (I In Covid Strings Seed List)
Const Round Div=Document.CreateElement
Round Div Class Name= Covid Strings1 Second Round
Bracket.AppendChild(Round Div)
If (Event.Target.Covid Strings Seed List.Contains(Matchup))
Event.Target.Covid Strings Seed List.Toggle
else:
create matchup
Import Java Util.Scanner
Import Java.Util
Questions[]Questions={
New Question27
New Question28
New Question29
New Question30
New Question31
New Question32
New Question33
New Question34
Substring(Start,End)
Userin.Mltiple Choice
If SelectedAnswer==Correct Answer:
Return True
Else:
Return False
AdvancingTeam=Current.Teams.Slice(CurrentTeams.Length)
DeclareWinner
If Team High Seed Score>=Sixty:
Let Result= DeclareWinner(Team1 Score, Team2 Score)
Console.Log( Team High Seed Wins Covid Strings1) 
Else:
Console.Log(Team Low Seed Wins Covid Strings1)
Return FileName
<BODY>
</HTML>

