doc.type.html
script
<header.html>
heading for heading variables
the variables used for headings and subheadings 
filename=covidstrings1 background.js
<header.html>
background overview
overview for covid strings 1 background
java.awt graphics
random button
new button(set random color)
option button
new j button (change color)
public fun with graphics()
color panel=new j panel();
add (panel,center)
button panel=
new j panel (new flowlayout(flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
<header.html>
background functions
functions used in covid strings 1 background 
colorpanel.setbackground(new color (rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen)))
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override
<header.html>
background code 
code for covid strings 1 background 
public actionperformed(actionevent e)
color multi=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args)
jframe= new covid strings1()
f.set title(covid strings1)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
object{a:one,b:two,c:three,d:four, e:five, f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
return filename
