doc.type.html
script
imagesrc =www.google.com/intl/en_com/images/logo_plain.png;
src = document.getelementbyid(covid virus)
getelementbyid
appendchild
getelementbyid
filename=covid strings1 .JS
java.awt graphics
audio = new audio
audio.play();
jbutton random button
new jbutton (set random color)
private final j button option button=
new j button (change color)
public fun with graphics(){
jpanel=color panel
add (panel,center )
add(button);
button add actionlistener(action listener)
override 
setbackground(new color)
panel add(optionbutton);
add actionlistener(action listener)
override 
public actionperformed(actionevent e){
showdialog(this)
if(background!=null)
set.Background
add(south)
jframe
set title(1)
set(exit_on_close);
setsize
set 
<label id=lblscore>zero</label>
(img) 
src =www.google.com/intl/en_com/images/logo_plain.png;
getelementbyid
appendchild
getelementbyid
score.InnerHTML
covidstrings1teamlist=[red protein spikers,orange rna messengers ,yellow moxie ,green peacemakers,burgundy rebuilders ,indigo isos,blue curve crushers,black night riders]
num teams
total players players per team
if players per team=0
return zero
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
phraselist=[non -concatenated hello covid world,dont eat bleach,could you please get vaccinated,good bye covid world,dont overcrowd hospital capacity,are we going back to 1918,there have been 100,000 reported deaths so far,the covid tracker shows] 
concatenated [you+should+get+tested,pfizer+is+95%+effective,you+should+not+forget+your+flu+shot,+snl+nailed+a+rona+christmas+there+have+been+some+negative+effects,+some+of+these+include+suicide,the+best+thing+to+do+is+practice+continuity+safely,+in+short+you+should+not+change+your+behavoir+much] 
math problems list=[if a covid value c equals 3 is added to the double of the value its equal to what do you get?, a covid value represented by a variable c is quadrupled and then added by f what is the resulting product?, if the cdcs covid tracker has 50,000 cases 35,000 cases were reported last week how many cases happened? the cov19 emergency alert system was installed on march 12 2020 after 2 weeks there were 1975 calls if the rate of calls was 5 per hour how many calls happened after the 1st week?, town a1s annual thanksgiving parade happens on november 19 a1s public health guidelines require that events of more than 20,000 people be held only if the positivity rate is <=5%  the current positivity rate is 6 1/3% and the parade is next week could it be held? if a decision could be made no later than the 16th and the amount of precautions taken include 10 cartons of 100 masks and 6ft of distancing can the parade still happen?]
[a+knock+off+vaccine+company+promises+to+deliver+a+vaccine+within+2+weeks+if+the+standard+timeline+is+4+weeks+how+much+damage+can+happen?
if+a+poll+on+this+question+showed+that+92 percent+of+republicans+thought+that+he+was+joking+when+it+came+to+bleach+how+many+cf+those+people+risked+illness?,if+875+people+were+reported+to+a+covid+hotline+because+they+thought+injecting+bleach+cured+covid+and+89%+of+them+said+they+believed+trump+how+many+people +out+of+the+total+believed+trump?
if+the+margin+of+error+is+fifty and five hundreths+percent+what+is+the+range?,a+news+report+suggested+that+the+level2+emergency+will+continue+for+another+week+if+the+rate+is+>3% if+it+is+currently+2.25%+would+it+continue? ,if + 4 people+ took+an+unknown+number+of+shots+from+pfizers+vaccine+at+3:45pm +on+october 7th when+would+it+expire?]
sentence list=[pfizer has a 95% effective vaccine,the+most+obvious+similarity+between+covid+and+the+spanish+flu+is+that+they+were+global+pandemics,any+covid+tracker+is+a+representation+of+data+at+a+specific+place+and+time]
multiple choice list=[1: a hydrogen peroxide,  b, ammonium nitrate, c bleach , d green eggs and ham 2: a rona, b green, c krona, d white 3: a tested, b a piercing, c a ti-82 graphing calculator, d a mcdonalds happy meal 4 : a bienvenu, b hello, c nihau, d hola 
5: a 55, b 95, c 88, d 66, 6 : a oversaturate, b overcrowd, c synthesize, d crowd-surf 7 : a flu, b meningits, c dogs rabies, d archery 8 : a tracker, b map, c graph positioning system, d lockdown 
9: a effects, b things, c results, d impacts 10: a snow throwing, b vaccinated, c off qanon, d snowballing 11: a 1918, b 1919, c -2045, d -1985 12: a 100,000 b a google, c a bevy, d a number zero sig figs 
13: a negative b netural c firework-like d wanting 14: a changes, b continuity, c sameness, d parity,  
15 :a behavoir, b outlook, c stress-level, d mindset, 16: a serum b vaccine c version mountain dew d gatorade knockoff,
17: a major b only c most obvious d glaring, 18: a hey-ey-ey goodybe, b sayornara, c good night, d goodbye, 19: a poll b prediction c doom scroll d tracker]
select 
import meta.
select 
(non-concatenated)
if question==math problem:
prompt
log 
else:
select from mutliple choice
if question==multiple choice:
select from multiple choice
else:
prompt
log
myclass=newmyclass(concatenated) 
return category
if question==math problem:
prompt
log
if question== multiple choice:
select from multiple choice
else:
prompt
log
import syntax 
substring(start,end)
userin.multiple choice
if select answer ==correct answer
log true
else
log false 
if selectedanswer=not correct:
return false
else:
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals((correctanswer))
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet) 
return filename
